name: Frontend Build CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
    build:
      runs-on: ubuntu-latest

      env:
        NEXT_PUBLIC_PROJECT_ID: ${{ secrets.WALLET_CONNECT_ID }}

      strategy:
        matrix:
          node-version: [ 18.x, 20.x ]

      steps:
        - uses: actions/checkout@v4

        - name: Cache turbo build setup
          uses: actions/cache@v4
          with:
            path: .turbo
            key: ${{ runner.os }}-turbo-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-turbo-

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: "yarn"

        - name: Install Dependencies
          run: yarn install --frozen-lockfile

        - name: Run Build
          run: yarn turbo run build --filter="@base-migrate/base-migrate-app" --cache-dir=.turbo

    lint:
      runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [ 18.x, 20.x ]

      steps:
        - uses: actions/checkout@v4

        - name: Cache turbo build setup
          uses: actions/cache@v4
          with:
            path: .turbo
            key: ${{ runner.os }}-turbo-${{ github.sha }}
            restore-keys: |
              ${{ runner.os }}-turbo-

        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: "yarn"

        - name: Install Dependencies
          run: yarn install --frozen-lockfile

        - name: Run Lint
          run: yarn turbo run lint --filter="@base-migrate/base-migrate-app" --cache-dir=.turbo
